/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosIdRouteImport } from './routes/produtos.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminAparenciaBannersRouteImport } from './routes/_authenticated/admin.aparencia.banners'
import { Route as AuthenticatedAdminAparenciaDestaquesRouteImport } from './routes/_authenticated/admin.aparencia.destaques'
import { Route as AuthenticatedAdminAparenciaHomeRouteImport } from './routes/_authenticated/admin.aparencia.home'
import { Route as AuthenticatedAdminConfigFreteRouteImport } from './routes/_authenticated/admin.config.frete'
import { Route as AuthenticatedAdminConfigIntegracoesRouteImport } from './routes/_authenticated/admin.config.integracoes'
import { Route as AuthenticatedAdminConfigLojaRouteImport } from './routes/_authenticated/admin.config.loja'
import { Route as AuthenticatedAdminConfigPagamentoRouteImport } from './routes/_authenticated/admin.config.pagamento'
import { Route as AuthenticatedAdminConfigSeoRouteImport } from './routes/_authenticated/admin.config.seo'
import { Route as AuthenticatedAdminRelatoriosClientesRouteImport } from './routes/_authenticated/admin.relatorios.clientes'
import { Route as AuthenticatedAdminRelatoriosExportarRouteImport } from './routes/_authenticated/admin.relatorios.exportar'
import { Route as AuthenticatedAdminRelatoriosMaisVendidosRouteImport } from './routes/_authenticated/admin.relatorios.mais-vendidos'
import { Route as AuthenticatedAdminRelatoriosVendasRouteImport } from './routes/_authenticated/admin.relatorios.vendas'
import { Route as AuthenticatedAdminSegurancaBackupRouteImport } from './routes/_authenticated/admin.seguranca.backup'
import { Route as AuthenticatedAdminSegurancaLoginRouteImport } from './routes/_authenticated/admin.seguranca.login'
import { Route as AuthenticatedAdminSegurancaLogsRouteImport } from './routes/_authenticated/admin.seguranca.logs'
import { Route as AuthenticatedAdminUsuariosAdminsRouteImport } from './routes/_authenticated/admin.usuarios.admins'
import { Route as AuthenticatedAdminUsuariosFuncionariosRouteImport } from './routes/_authenticated/admin.usuarios.funcionarios'
import { Route as AuthenticatedAdminUsuariosPermissoesRouteImport } from './routes/_authenticated/admin.usuarios.permissoes'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdutosRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAparenciaBannersRoute =
  AuthenticatedAdminAparenciaBannersRouteImport.update({
    id: '/aparencia/banners',
    path: '/aparencia/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAparenciaDestaquesRoute =
  AuthenticatedAdminAparenciaDestaquesRouteImport.update({
    id: '/aparencia/destaques',
    path: '/aparencia/destaques',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAparenciaHomeRoute =
  AuthenticatedAdminAparenciaHomeRouteImport.update({
    id: '/aparencia/home',
    path: '/aparencia/home',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigFreteRoute =
  AuthenticatedAdminConfigFreteRouteImport.update({
    id: '/config/frete',
    path: '/config/frete',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigIntegracoesRoute =
  AuthenticatedAdminConfigIntegracoesRouteImport.update({
    id: '/config/integracoes',
    path: '/config/integracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigLojaRoute =
  AuthenticatedAdminConfigLojaRouteImport.update({
    id: '/config/loja',
    path: '/config/loja',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigPagamentoRoute =
  AuthenticatedAdminConfigPagamentoRouteImport.update({
    id: '/config/pagamento',
    path: '/config/pagamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfigSeoRoute =
  AuthenticatedAdminConfigSeoRouteImport.update({
    id: '/config/seo',
    path: '/config/seo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosClientesRoute =
  AuthenticatedAdminRelatoriosClientesRouteImport.update({
    id: '/relatorios/clientes',
    path: '/relatorios/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosExportarRoute =
  AuthenticatedAdminRelatoriosExportarRouteImport.update({
    id: '/relatorios/exportar',
    path: '/relatorios/exportar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosMaisVendidosRoute =
  AuthenticatedAdminRelatoriosMaisVendidosRouteImport.update({
    id: '/relatorios/mais-vendidos',
    path: '/relatorios/mais-vendidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosVendasRoute =
  AuthenticatedAdminRelatoriosVendasRouteImport.update({
    id: '/relatorios/vendas',
    path: '/relatorios/vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegurancaBackupRoute =
  AuthenticatedAdminSegurancaBackupRouteImport.update({
    id: '/seguranca/backup',
    path: '/seguranca/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegurancaLoginRoute =
  AuthenticatedAdminSegurancaLoginRouteImport.update({
    id: '/seguranca/login',
    path: '/seguranca/login',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegurancaLogsRoute =
  AuthenticatedAdminSegurancaLogsRouteImport.update({
    id: '/seguranca/logs',
    path: '/seguranca/logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosAdminsRoute =
  AuthenticatedAdminUsuariosAdminsRouteImport.update({
    id: '/usuarios/admins',
    path: '/usuarios/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosFuncionariosRoute =
  AuthenticatedAdminUsuariosFuncionariosRouteImport.update({
    id: '/usuarios/funcionarios',
    path: '/usuarios/funcionarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosPermissoesRoute =
  AuthenticatedAdminUsuariosPermissoesRouteImport.update({
    id: '/usuarios/permissoes',
    path: '/usuarios/permissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/ofertas': typeof OfertasRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/conta': typeof AuthenticatedContaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/aparencia/banners': typeof AuthenticatedAdminAparenciaBannersRoute
  '/admin/aparencia/destaques': typeof AuthenticatedAdminAparenciaDestaquesRoute
  '/admin/aparencia/home': typeof AuthenticatedAdminAparenciaHomeRoute
  '/admin/config/frete': typeof AuthenticatedAdminConfigFreteRoute
  '/admin/config/integracoes': typeof AuthenticatedAdminConfigIntegracoesRoute
  '/admin/config/loja': typeof AuthenticatedAdminConfigLojaRoute
  '/admin/config/pagamento': typeof AuthenticatedAdminConfigPagamentoRoute
  '/admin/config/seo': typeof AuthenticatedAdminConfigSeoRoute
  '/admin/relatorios/clientes': typeof AuthenticatedAdminRelatoriosClientesRoute
  '/admin/relatorios/exportar': typeof AuthenticatedAdminRelatoriosExportarRoute
  '/admin/relatorios/mais-vendidos': typeof AuthenticatedAdminRelatoriosMaisVendidosRoute
  '/admin/relatorios/vendas': typeof AuthenticatedAdminRelatoriosVendasRoute
  '/admin/seguranca/backup': typeof AuthenticatedAdminSegurancaBackupRoute
  '/admin/seguranca/login': typeof AuthenticatedAdminSegurancaLoginRoute
  '/admin/seguranca/logs': typeof AuthenticatedAdminSegurancaLogsRoute
  '/admin/usuarios/admins': typeof AuthenticatedAdminUsuariosAdminsRoute
  '/admin/usuarios/funcionarios': typeof AuthenticatedAdminUsuariosFuncionariosRoute
  '/admin/usuarios/permissoes': typeof AuthenticatedAdminUsuariosPermissoesRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/ofertas': typeof OfertasRoute
  '/conta': typeof AuthenticatedContaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/aparencia/banners': typeof AuthenticatedAdminAparenciaBannersRoute
  '/admin/aparencia/destaques': typeof AuthenticatedAdminAparenciaDestaquesRoute
  '/admin/aparencia/home': typeof AuthenticatedAdminAparenciaHomeRoute
  '/admin/config/frete': typeof AuthenticatedAdminConfigFreteRoute
  '/admin/config/integracoes': typeof AuthenticatedAdminConfigIntegracoesRoute
  '/admin/config/loja': typeof AuthenticatedAdminConfigLojaRoute
  '/admin/config/pagamento': typeof AuthenticatedAdminConfigPagamentoRoute
  '/admin/config/seo': typeof AuthenticatedAdminConfigSeoRoute
  '/admin/relatorios/clientes': typeof AuthenticatedAdminRelatoriosClientesRoute
  '/admin/relatorios/exportar': typeof AuthenticatedAdminRelatoriosExportarRoute
  '/admin/relatorios/mais-vendidos': typeof AuthenticatedAdminRelatoriosMaisVendidosRoute
  '/admin/relatorios/vendas': typeof AuthenticatedAdminRelatoriosVendasRoute
  '/admin/seguranca/backup': typeof AuthenticatedAdminSegurancaBackupRoute
  '/admin/seguranca/login': typeof AuthenticatedAdminSegurancaLoginRoute
  '/admin/seguranca/logs': typeof AuthenticatedAdminSegurancaLogsRoute
  '/admin/usuarios/admins': typeof AuthenticatedAdminUsuariosAdminsRoute
  '/admin/usuarios/funcionarios': typeof AuthenticatedAdminUsuariosFuncionariosRoute
  '/admin/usuarios/permissoes': typeof AuthenticatedAdminUsuariosPermissoesRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/favoritos': typeof FavoritosRoute
  '/ofertas': typeof OfertasRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/aparencia/banners': typeof AuthenticatedAdminAparenciaBannersRoute
  '/_authenticated/admin/aparencia/destaques': typeof AuthenticatedAdminAparenciaDestaquesRoute
  '/_authenticated/admin/aparencia/home': typeof AuthenticatedAdminAparenciaHomeRoute
  '/_authenticated/admin/config/frete': typeof AuthenticatedAdminConfigFreteRoute
  '/_authenticated/admin/config/integracoes': typeof AuthenticatedAdminConfigIntegracoesRoute
  '/_authenticated/admin/config/loja': typeof AuthenticatedAdminConfigLojaRoute
  '/_authenticated/admin/config/pagamento': typeof AuthenticatedAdminConfigPagamentoRoute
  '/_authenticated/admin/config/seo': typeof AuthenticatedAdminConfigSeoRoute
  '/_authenticated/admin/relatorios/clientes': typeof AuthenticatedAdminRelatoriosClientesRoute
  '/_authenticated/admin/relatorios/exportar': typeof AuthenticatedAdminRelatoriosExportarRoute
  '/_authenticated/admin/relatorios/mais-vendidos': typeof AuthenticatedAdminRelatoriosMaisVendidosRoute
  '/_authenticated/admin/relatorios/vendas': typeof AuthenticatedAdminRelatoriosVendasRoute
  '/_authenticated/admin/seguranca/backup': typeof AuthenticatedAdminSegurancaBackupRoute
  '/_authenticated/admin/seguranca/login': typeof AuthenticatedAdminSegurancaLoginRoute
  '/_authenticated/admin/seguranca/logs': typeof AuthenticatedAdminSegurancaLogsRoute
  '/_authenticated/admin/usuarios/admins': typeof AuthenticatedAdminUsuariosAdminsRoute
  '/_authenticated/admin/usuarios/funcionarios': typeof AuthenticatedAdminUsuariosFuncionariosRoute
  '/_authenticated/admin/usuarios/permissoes': typeof AuthenticatedAdminUsuariosPermissoesRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/favoritos'
    | '/ofertas'
    | '/produtos'
    | '/admin'
    | '/conta'
    | '/categoria/$slug'
    | '/produtos/$id'
    | '/produtos/'
    | '/admin/clientes'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/aparencia/banners'
    | '/admin/aparencia/destaques'
    | '/admin/aparencia/home'
    | '/admin/config/frete'
    | '/admin/config/integracoes'
    | '/admin/config/loja'
    | '/admin/config/pagamento'
    | '/admin/config/seo'
    | '/admin/relatorios/clientes'
    | '/admin/relatorios/exportar'
    | '/admin/relatorios/mais-vendidos'
    | '/admin/relatorios/vendas'
    | '/admin/seguranca/backup'
    | '/admin/seguranca/login'
    | '/admin/seguranca/logs'
    | '/admin/usuarios/admins'
    | '/admin/usuarios/funcionarios'
    | '/admin/usuarios/permissoes'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/favoritos'
    | '/ofertas'
    | '/conta'
    | '/categoria/$slug'
    | '/produtos/$id'
    | '/produtos'
    | '/admin/clientes'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
    | '/admin/aparencia/banners'
    | '/admin/aparencia/destaques'
    | '/admin/aparencia/home'
    | '/admin/config/frete'
    | '/admin/config/integracoes'
    | '/admin/config/loja'
    | '/admin/config/pagamento'
    | '/admin/config/seo'
    | '/admin/relatorios/clientes'
    | '/admin/relatorios/exportar'
    | '/admin/relatorios/mais-vendidos'
    | '/admin/relatorios/vendas'
    | '/admin/seguranca/backup'
    | '/admin/seguranca/login'
    | '/admin/seguranca/logs'
    | '/admin/usuarios/admins'
    | '/admin/usuarios/funcionarios'
    | '/admin/usuarios/permissoes'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/favoritos'
    | '/ofertas'
    | '/produtos'
    | '/_authenticated/admin'
    | '/_authenticated/conta'
    | '/categoria/$slug'
    | '/produtos/$id'
    | '/produtos/'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/aparencia/banners'
    | '/_authenticated/admin/aparencia/destaques'
    | '/_authenticated/admin/aparencia/home'
    | '/_authenticated/admin/config/frete'
    | '/_authenticated/admin/config/integracoes'
    | '/_authenticated/admin/config/loja'
    | '/_authenticated/admin/config/pagamento'
    | '/_authenticated/admin/config/seo'
    | '/_authenticated/admin/relatorios/clientes'
    | '/_authenticated/admin/relatorios/exportar'
    | '/_authenticated/admin/relatorios/mais-vendidos'
    | '/_authenticated/admin/relatorios/vendas'
    | '/_authenticated/admin/seguranca/backup'
    | '/_authenticated/admin/seguranca/login'
    | '/_authenticated/admin/seguranca/logs'
    | '/_authenticated/admin/usuarios/admins'
    | '/_authenticated/admin/usuarios/funcionarios'
    | '/_authenticated/admin/usuarios/permissoes'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritosRoute: typeof FavoritosRoute
  OfertasRoute: typeof OfertasRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aparencia/banners': {
      id: '/_authenticated/admin/aparencia/banners'
      path: '/aparencia/banners'
      fullPath: '/admin/aparencia/banners'
      preLoaderRoute: typeof AuthenticatedAdminAparenciaBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aparencia/destaques': {
      id: '/_authenticated/admin/aparencia/destaques'
      path: '/aparencia/destaques'
      fullPath: '/admin/aparencia/destaques'
      preLoaderRoute: typeof AuthenticatedAdminAparenciaDestaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aparencia/home': {
      id: '/_authenticated/admin/aparencia/home'
      path: '/aparencia/home'
      fullPath: '/admin/aparencia/home'
      preLoaderRoute: typeof AuthenticatedAdminAparenciaHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config/frete': {
      id: '/_authenticated/admin/config/frete'
      path: '/config/frete'
      fullPath: '/admin/config/frete'
      preLoaderRoute: typeof AuthenticatedAdminConfigFreteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config/integracoes': {
      id: '/_authenticated/admin/config/integracoes'
      path: '/config/integracoes'
      fullPath: '/admin/config/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfigIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config/loja': {
      id: '/_authenticated/admin/config/loja'
      path: '/config/loja'
      fullPath: '/admin/config/loja'
      preLoaderRoute: typeof AuthenticatedAdminConfigLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config/pagamento': {
      id: '/_authenticated/admin/config/pagamento'
      path: '/config/pagamento'
      fullPath: '/admin/config/pagamento'
      preLoaderRoute: typeof AuthenticatedAdminConfigPagamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config/seo': {
      id: '/_authenticated/admin/config/seo'
      path: '/config/seo'
      fullPath: '/admin/config/seo'
      preLoaderRoute: typeof AuthenticatedAdminConfigSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios/clientes': {
      id: '/_authenticated/admin/relatorios/clientes'
      path: '/relatorios/clientes'
      fullPath: '/admin/relatorios/clientes'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios/exportar': {
      id: '/_authenticated/admin/relatorios/exportar'
      path: '/relatorios/exportar'
      fullPath: '/admin/relatorios/exportar'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosExportarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios/mais-vendidos': {
      id: '/_authenticated/admin/relatorios/mais-vendidos'
      path: '/relatorios/mais-vendidos'
      fullPath: '/admin/relatorios/mais-vendidos'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosMaisVendidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios/vendas': {
      id: '/_authenticated/admin/relatorios/vendas'
      path: '/relatorios/vendas'
      fullPath: '/admin/relatorios/vendas'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seguranca/backup': {
      id: '/_authenticated/admin/seguranca/backup'
      path: '/seguranca/backup'
      fullPath: '/admin/seguranca/backup'
      preLoaderRoute: typeof AuthenticatedAdminSegurancaBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seguranca/login': {
      id: '/_authenticated/admin/seguranca/login'
      path: '/seguranca/login'
      fullPath: '/admin/seguranca/login'
      preLoaderRoute: typeof AuthenticatedAdminSegurancaLoginRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seguranca/logs': {
      id: '/_authenticated/admin/seguranca/logs'
      path: '/seguranca/logs'
      fullPath: '/admin/seguranca/logs'
      preLoaderRoute: typeof AuthenticatedAdminSegurancaLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios/admins': {
      id: '/_authenticated/admin/usuarios/admins'
      path: '/usuarios/admins'
      fullPath: '/admin/usuarios/admins'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios/funcionarios': {
      id: '/_authenticated/admin/usuarios/funcionarios'
      path: '/usuarios/funcionarios'
      fullPath: '/admin/usuarios/funcionarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios/permissoes': {
      id: '/_authenticated/admin/usuarios/permissoes'
      path: '/usuarios/permissoes'
      fullPath: '/admin/usuarios/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAparenciaBannersRoute: typeof AuthenticatedAdminAparenciaBannersRoute
  AuthenticatedAdminAparenciaDestaquesRoute: typeof AuthenticatedAdminAparenciaDestaquesRoute
  AuthenticatedAdminAparenciaHomeRoute: typeof AuthenticatedAdminAparenciaHomeRoute
  AuthenticatedAdminConfigFreteRoute: typeof AuthenticatedAdminConfigFreteRoute
  AuthenticatedAdminConfigIntegracoesRoute: typeof AuthenticatedAdminConfigIntegracoesRoute
  AuthenticatedAdminConfigLojaRoute: typeof AuthenticatedAdminConfigLojaRoute
  AuthenticatedAdminConfigPagamentoRoute: typeof AuthenticatedAdminConfigPagamentoRoute
  AuthenticatedAdminConfigSeoRoute: typeof AuthenticatedAdminConfigSeoRoute
  AuthenticatedAdminRelatoriosClientesRoute: typeof AuthenticatedAdminRelatoriosClientesRoute
  AuthenticatedAdminRelatoriosExportarRoute: typeof AuthenticatedAdminRelatoriosExportarRoute
  AuthenticatedAdminRelatoriosMaisVendidosRoute: typeof AuthenticatedAdminRelatoriosMaisVendidosRoute
  AuthenticatedAdminRelatoriosVendasRoute: typeof AuthenticatedAdminRelatoriosVendasRoute
  AuthenticatedAdminSegurancaBackupRoute: typeof AuthenticatedAdminSegurancaBackupRoute
  AuthenticatedAdminSegurancaLoginRoute: typeof AuthenticatedAdminSegurancaLoginRoute
  AuthenticatedAdminSegurancaLogsRoute: typeof AuthenticatedAdminSegurancaLogsRoute
  AuthenticatedAdminUsuariosAdminsRoute: typeof AuthenticatedAdminUsuariosAdminsRoute
  AuthenticatedAdminUsuariosFuncionariosRoute: typeof AuthenticatedAdminUsuariosFuncionariosRoute
  AuthenticatedAdminUsuariosPermissoesRoute: typeof AuthenticatedAdminUsuariosPermissoesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAparenciaBannersRoute:
    AuthenticatedAdminAparenciaBannersRoute,
  AuthenticatedAdminAparenciaDestaquesRoute:
    AuthenticatedAdminAparenciaDestaquesRoute,
  AuthenticatedAdminAparenciaHomeRoute: AuthenticatedAdminAparenciaHomeRoute,
  AuthenticatedAdminConfigFreteRoute: AuthenticatedAdminConfigFreteRoute,
  AuthenticatedAdminConfigIntegracoesRoute:
    AuthenticatedAdminConfigIntegracoesRoute,
  AuthenticatedAdminConfigLojaRoute: AuthenticatedAdminConfigLojaRoute,
  AuthenticatedAdminConfigPagamentoRoute:
    AuthenticatedAdminConfigPagamentoRoute,
  AuthenticatedAdminConfigSeoRoute: AuthenticatedAdminConfigSeoRoute,
  AuthenticatedAdminRelatoriosClientesRoute:
    AuthenticatedAdminRelatoriosClientesRoute,
  AuthenticatedAdminRelatoriosExportarRoute:
    AuthenticatedAdminRelatoriosExportarRoute,
  AuthenticatedAdminRelatoriosMaisVendidosRoute:
    AuthenticatedAdminRelatoriosMaisVendidosRoute,
  AuthenticatedAdminRelatoriosVendasRoute:
    AuthenticatedAdminRelatoriosVendasRoute,
  AuthenticatedAdminSegurancaBackupRoute:
    AuthenticatedAdminSegurancaBackupRoute,
  AuthenticatedAdminSegurancaLoginRoute: AuthenticatedAdminSegurancaLoginRoute,
  AuthenticatedAdminSegurancaLogsRoute: AuthenticatedAdminSegurancaLogsRoute,
  AuthenticatedAdminUsuariosAdminsRoute: AuthenticatedAdminUsuariosAdminsRoute,
  AuthenticatedAdminUsuariosFuncionariosRoute:
    AuthenticatedAdminUsuariosFuncionariosRoute,
  AuthenticatedAdminUsuariosPermissoesRoute:
    AuthenticatedAdminUsuariosPermissoesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProdutosRouteChildren {
  ProdutosIdRoute: typeof ProdutosIdRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosIdRoute: ProdutosIdRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritosRoute: FavoritosRoute,
  OfertasRoute: OfertasRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
